sudo:              false

language:          python

cache:             pip

python:            3.6.5

branches:          master

before_install:
  - pip install -r requirements.txt

install:
  - wget https://rawgit.com/ShinyArceus1/SOS-Code/master/code/sos.py
  - svn export https://github.com/Richienb/ROS-Code/src/ros ros

script:
  - python game.py

before_deploy:
  - svn export https://github.com/hfagerlund/mkdocs-docskimmer/mkdocs_docskimmer mkdocs_theme
  - cp -r ./mkdocs_theme .
  - cp -r ./mkdocs_theme/. ./docs
  - mkdocs build --verbose --clean

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master

notifications:
  email:           false
