sudo:              false

language:          python

cache:             pip

python:            3.6.6

branches:          master

before_install:
  - pip install -r requirements.txt

install:
  - wget https://rawgit.com/ShinyArceus1/SOS-Code/master/code/sos.py
  - wget https://rawgit.com/Richienb/ROS-Code/master/Makefile && make prepare && rm -f run_file.py && rm -f Makefile

script:
  - python game.py

before_deploy:
  - git clone https://github.com/hfagerlund/mkdocs-docskimmer mkdocs_theme_source && cp ./mkdocs_theme_source/mkdocs_docskimmer .
  - cp -r ./mkdocs_theme .
  - cp -r ./mkdocs_theme/. ./docs
  - mkdocs build --verbose --clean

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master

notifications:
  email:           false
