sudo:              false

language:          python

python:
  - 3.6.5

branches:
  - master

before_install:
  - pip install -r requirements.txt

install:
  - git clone https://github.com/ShinyArceus1/SOS-Code.git
  - cp -r $PWD/SOS-Code/code/sos.py .
  - git clone https://github.com/Richienb/ROS-Code.git
  - mv $PWD/ROS-Code/src/syntax.py $PWD/ROS-Code/src/ros.py
  - cp -r $PWD/ROS-Code/src/ros.py .

script:
  - python game.py

before_deploy:
  - git clone https://github.com/hfagerlund/mkdocs-docskimmer.git
  - cp -r $PWD/mkdocs-docskimmer/mkdocs_docskimmer .
  - cp -r $PWD/mkdocs-docskimmer/mkdocs_docskimmer/. ./docs
  - mkdocs build --verbose --clean

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master

notifications:
  email:           false
